<?php
// database/seeders/SedesSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SedesSeeder extends Seeder
{
    public function run(): void
    {
        $sedes = [
            ['nom_sede' => 'TIC', 'centro_id' => 23, 'matricula_inmobiliario' => '', 'barrio_sede' => 'EL PRADO', 'direc_sede' => 'CRA 54 N°68-80', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/tic_nodo_nehiq3lt.jpg","usrName":"tic_nodo.jpg","size":61265,"type":"image\\/jpeg","searchStr":"tic_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-12 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'CONSTRUCCION', 'centro_id' => 24, 'matricula_inmobiliario' => '', 'barrio_sede' => 'VILLAS DE SAN PEDRO', 'direc_sede' => 'MF EQ 8 LOTE', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/construccion_nodo_ii1vpced.jpeg","usrName":"construccion_nodo.jpeg","size":39400,"type":"image\\/jpeg","searchStr":"construccion_nodo.jpeg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-20 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'ENERGIA', 'centro_id' => 23, 'matricula_inmobiliario' => '', 'barrio_sede' => 'MONTES', 'direc_sede' => 'CALLE 28 N°23-18', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/energia_nodo_q81ye6u9.jpg","usrName":"energia_nodo.jpg","size":58297,"type":"image\\/jpeg","searchStr":"energia_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'REFRIGERACIÓN', 'centro_id' => 23, 'matricula_inmobiliario' => '', 'barrio_sede' => 'LIPAYA', 'direc_sede' => 'CARRERA 10 N°73 E-101', 'localidad' => '', 'img_sede' => '[{"name":"files\\/refrigeracion_nodo_mhpy48e5.jpg","usrName":"refrigeracion_nodo.jpg","size":82666,"type":"image\\/jpeg","searchStr":"refrigeracion_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'METALMECANICA', 'centro_id' => 23, 'matricula_inmobiliario' => '', 'barrio_sede' => 'MALAMBO', 'direc_sede' => 'N°16-A16-123', 'localidad' => 'MALAMBO', 'img_sede' => '[{"name":"files\\/metalmecanica_nodo_b7jeen55.jpg","usrName":"metalmecanica_nodo.jpg","size":26283,"type":"image\\/jpeg","searchStr":"metalmecanica_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SEDE PRINCIPAL CENTRO NACIONAL COLOMBO ALEMAN', 'centro_id' => 23, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SANTA ELENA', 'direc_sede' => 'CALLE 30 N° 3E-164', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/colombo_nodo_3yio6qua.jpg","usrName":"colombo_nodo.jpg","size":44128,"type":"image\\/jpeg","searchStr":"colombo_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'CONFECCIONES', 'centro_id' => 24, 'matricula_inmobiliario' => '', 'barrio_sede' => 'BARANOA', 'direc_sede' => 'CALLE 12#19-221', 'localidad' => 'BARANOA', 'img_sede' => '[{"name":"files\\/confecciones_nodo_twlbzbj9.jpeg","usrName":"confecciones_nodo.jpeg","size":37224,"type":"image\\/jpeg","searchStr":"confecciones_nodo.jpeg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'MULTILINGUISMO', 'centro_id' => 24, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SAN JOSE', 'direc_sede' => 'CARRERA 21 B CALLE 40B', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/multilinguismo_nodo_e0e43xip.jpeg","usrName":"multilinguismo_nodo.jpeg","size":52421,"type":"image\\/jpeg","searchStr":"multilinguismo_nodo.jpeg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'DISEÑO Y MOBILIARIO', 'centro_id' => 24, 'matricula_inmobiliario' => '', 'barrio_sede' => 'GALAPA', 'direc_sede' => 'CALLE 7B ENTRE CARRERA 55 Y 56', 'localidad' => 'GALAPA', 'img_sede' => '[{"name":"files\\/dise__o y mobiliario_nodo_k77o77rm.jpeg","usrName":"diseño y mobiliario_nodo.jpeg","size":26473,"type":"image\\/jpeg","searchStr":"diseño y mobiliario_nodo.jpeg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SEDE PRINCIPAL CENTRO INDUSTRIAL Y DE AVIACION', 'centro_id' => 24, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SANTA ELENA', 'direc_sede' => 'CALLE 30 N° 3E-164', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/sede industrial_nodo_xn1gsxnf.jpeg","usrName":"sede industrial_nodo.jpeg","size":53441,"type":"image\\/jpeg","searchStr":"sede industrial_nodo.jpeg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'INDUSTRIAS CREATIVAS', 'centro_id' => 22, 'matricula_inmobiliario' => '', 'barrio_sede' => 'BARRIO ABAJO', 'direc_sede' => 'CRA 54 N° 49-09', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/industriasCrea_nodo_1atejvna.jpg","usrName":"industriasCrea_nodo.jpg","size":46546,"type":"image\\/jpeg","searchStr":"industriasCrea_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'ECOTURISMO Y GASTRONOMICO', 'centro_id' => 22, 'matricula_inmobiliario' => '', 'barrio_sede' => 'LURUACO', 'direc_sede' => 'CARRERA 9A N° 127', 'localidad' => 'LURUACO', 'img_sede' => '[{"name":"files\\/ecoturismo_nodo_57bha9qw.jpg","usrName":"ecoturismo_nodo.jpg","size":55281,"type":"image\\/jpeg","searchStr":"ecoturismo_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'OPERACIONES COMERCIALES', 'centro_id' => 22, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SOLEDAD', 'direc_sede' => 'CARRETERA ORIENTAL', 'localidad' => 'SOLEDAD', 'img_sede' => '[{"name":"files\\/op_comerciales_nodo2_y3ecudee.png","usrName":"op_comerciales_nodo2.png","size":374933,"type":"image\\/png","searchStr":"op_comerciales_nodo2.png,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SEDE PRINCIPAL CENTRO CEDAGRO', 'centro_id' => 22, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SABANALARGA', 'direc_sede' => 'CALLE9#19-120', 'localidad' => 'SABANA-LARGA', 'img_sede' => '[{"name":"files\\/cedagro_nodo_2v6ogg18.jfif","usrName":"cedagro_nodo.jfif","size":48767,"type":"image\\/jpeg","searchStr":"cedagro_nodo.jfif,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SEDE FINCA EL CANEY', 'centro_id' => 22, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SABANALARGA', 'direc_sede' => 'KM,CL.35', 'localidad' => 'SABANALARGA', 'img_sede' => '[{"name":"files\\/el caney_0bzmxdv9.png","usrName":"el caney.png","size":390434,"type":"image\\/png","searchStr":"el caney.png,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SALUD Y CUIDADO PERSONAL', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'SAN ROQUE', 'direc_sede' => 'CALLE 33 N°33-139', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/salud_nodo_79kiiqyx.jpg","usrName":"salud_nodo.jpg","size":59555,"type":"image\\/jpeg","searchStr":"salud_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'LOGISTICA Y TRANSPORTE', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'URBANIZACION EL PARQUE', 'direc_sede' => 'CARRERA 9A N°127-109', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/logistica_nodo_i7kvsfg8.jpg","usrName":"logistica_nodo.jpg","size":35896,"type":"image\\/jpeg","searchStr":"logistica_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'HOTELERIA Y TURISMO', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'BARRIO ABAJO', 'direc_sede' => 'CALLE 39 N° 50-89', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/hoteleria_nodo_k6ohcuga.jpg","usrName":"hoteleria_nodo.jpg","size":39050,"type":"image\\/jpeg","searchStr":"hoteleria_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SERVICIOS ADMINISTRATIVOS', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'EL BOSQUE', 'direc_sede' => 'CARRERA 6N° 60B-110', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/servicios_admin_nodo_wyhlb07i.jpg","usrName":"servicios_admin_nodo.jpg","size":52312,"type":"image\\/jpeg","searchStr":"servicios_admin_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SERVICIOS FINANCIEROS', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'LAS CAYENAS', 'direc_sede' => 'CARRERA 15 SUR N° 46-500', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/servicios_finan_nodo_1bktrihb.jpg","usrName":"servicios_finan_nodo.jpg","size":39546,"type":"image\\/jpeg","searchStr":"servicios_finan_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'COMERCIALIZACION', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'LAS CAYENAS', 'direc_sede' => 'CARRERA 15 SUR N° 46-500', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/comercializacion_nodo_r7uffut6.jpg","usrName":"comercializacion_nodo.jpg","size":45907,"type":"image\\/jpeg","searchStr":"comercializacion_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'SEDE PRINCIPAL CENTRO COMERCIO Y SERVICIO', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'CENTRO', 'direc_sede' => 'C4 CARRERA 43 N° 42-40', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/comercio_nodo_81oy6ssw.jpg","usrName":"comercio_nodo.jpg","size":58006,"type":"image\\/jpeg","searchStr":"comercio_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'GASTRONOMIA Y BILINGUISMO', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'JUAN DE COSTA', 'direc_sede' => 'CALLE 9 N° 1D-125', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/gastronomia_nodo_kuwgo3n8.jpeg","usrName":"gastronomia_nodo.jpeg","size":38203,"type":"image\\/jpeg","searchStr":"gastronomia_nodo.jpeg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'NODO PALERMO', 'centro_id' => 25, 'matricula_inmobiliario' => '', 'barrio_sede' => 'PALERMO', 'direc_sede' => 'CORREDOR DE CARGA SITIO NUEVO', 'localidad' => 'BARRANQUILLA', 'img_sede' => '[{"name":"files\\/palermo_nodo_r7b4kzml.jpg","usrName":"palermo_nodo.jpg","size":10385,"type":"image\\/jpeg","searchStr":"palermo_nodo.jpg,!:sStrEnd"}]', 'fecha_reg_sede' => '2023-09-13 00:00:00', 'descripcion' => null],
            ['nom_sede' => 'despacho', 'centro_id' => 21, 'matricula_inmobiliario' => '', 'barrio_sede' => '', 'direc_sede' => '', 'localidad' => 'BARRANQUILLA', 'img_sede' => '', 'fecha_reg_sede' => null, 'descripcion' => null]
        ];

        foreach ($sedes as $sede) {
            DB::table('sedes')->insert(array_merge($sede, [
                'created_at' => now(),
                'updated_at' => now()
            ]));
        }
    }
}